sudo: required
services:
  - docker


before_install:
  - docker build -f Dockerfile.dev -t nerdpad/tut-docker-react .

script:
  - docker run nerdpad/tut-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "tut-docker-react"
  env: "TutDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-045913666253"
  bucket_path: "tut-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
